
<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à Sans-Atout</title>
<meta charset="UTF-8">
<title style="font-size:300%:"></title>
</head>

<body> 
Jeu avec le Mort à Sans-Atout</>

<p> <a href="../progresser.php">Retour</a>

<pre>
<h1> 15 - Plan de jeu et choix (252 donnes) </h1>

<h2> 1 - 1 - Preference a l'affranchissement (29 Donnes) </h2> 
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=XTxRmakn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=t7DySzxJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=4NFGxE9g" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=NeB5nZcV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=aZbrYLKi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=yh7dwqZv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=WcfDi489" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=nGc8pi53" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=rKJjVzQa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=NCptfuXK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=fNeFVxbD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=THDWPn7V" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=9xW8bgid" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=qzrXkx8g" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=6wNnJGEy" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=urc8qPyh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=jTeAWuyb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=r5hYbx7q" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=vYmtfFgL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=YQ6u8zdP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=QVYHSe9U" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=KGb5JnH9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=vAnMqeHb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=GT6wVYnX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=KvupqDJ2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=fGgXHNK2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=5vPsDufg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=9KGPN86t" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=3P7iFQuA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/1_-_Preference_a_l'affranchissement/Donne_29.lin" target="_blank">Solution</a>

<h2> 2 - Choix entre repartitions (26 Donnes)  </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=5qDi79UP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=4DcKGFij" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=97D8wXKP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=WdkbHacS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=gTMBsUyP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=MgqH4XbN" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=a8sFQWZj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=tdqQbgYs" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=QagGbDuN" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=LMkpUG6v" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=h6X37FUv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=jf8GULHS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=nRgsj8D3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=xC7TtzJL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=RwNFn3aM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=7p29kMTm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=ZXTYQ52G" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=xfe8DKwA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=GaDE7u6Y" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=7C6ufABE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=ztZn5gbp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=tHiyhPqY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=2UJ6wHTg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=Uti9HgGR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=FqEhbvzx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=fkhX7pU5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/2_-_Choix_entre_repartitions/Donne_26.lin" target="_blank">Solution</a>

<h2> 3 - Repartition ou impasse (11 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=8YXLAxFm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=P2ZDrM6Y" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=8iF9H4Zk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=S3hmZgVs" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=C5SfiuMX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=CDrJQ2Wv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=cjJtUZp8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=wtg3qarQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=FRVmet5G" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=pXHMJEhb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=R3kEaA6W" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/3_-_Repartition_ou_impasse/Donne_11.lin" target="_blank">Solution</a>

<h2>  4.1 - Impasse plutot qu'affranchissement (9 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=xC8wbNmE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=KrQF39iJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=naML63bm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=cnFV3jYW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=kT5QbyJW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=Vz7WiGum" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=fGpLC2hj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=ruqgsP3w" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=haxHG3KS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.1_-_Impasse_plutot_qu'affranchissement/Donne_9.lin" target="_blank">Solution</a>

<h2> 4.2 - Impasse plutot que repartition (19 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=Ki7qRU2g" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=7ZSy5muA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=KTByA8sF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=xAYZzEJy" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=bdag4ws3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=hPuC9aZG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=aHdsycxz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=y3ir6YSq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=pYMhPrjw" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=GJD6y9LR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=Hj5YLbUM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=WQ6dG75q" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=U5tBfu2i" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=i9uUcJ4h" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=xDisguqt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=nuKWRsAM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=8pFY2aK4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=QHdy4zeC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=LJnXmd83" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/4.2_-_Impasse_plutot_que_repartition/Donne_19.lin" target="_blank">Solution</a>

<h2> 5 - Choix entre impasses (27 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=VupnAXtF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=EZTcAybt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=FkNMaxuB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=i3eq6uS4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=FkNMaxuB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=WXDzGyUV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=jEimtcKX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=fSimGKuW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=YDkA68ui" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=W8nQSMD9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=t6PEULxD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=9G5BqZeE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=5MtgwurA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=4GtascXf" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=nKsY6NLD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=VJfQg6d4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=DW3wnG7p" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=LvcB6rhm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=HkP6uXDj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=jP6vfN3U" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=QJ4GD28n" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=fJDeMY6W" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=CNY8z4Zk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=FRtN9DXu" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=gjT65kRK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=aju4Xs9C" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=ZMN9XveR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_entre_impasses/Donne_27.lin" target="_blank">Solution</a>

<h2> 6 - Le choix de la couleur a exploiter (47 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=jAxUD6Pd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=kS7jPiHA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=giZc7pTk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=V3EpgX8e" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=aX3dHhER" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=mcTGw3hu" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=bLgk8MDU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=bihSacjn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=8ZA6JH92" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=WvEG4u7r" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=nGc8pi53" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=p85Di6bX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=2AkfmrQD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/5_-_Choix_de_la_couleur_a_exploiter/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=sGZcpweX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=rKJjVzQa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=bLgk8MDU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=bihSacjn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=4xXzPkZ7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=UmAYNFW3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=fxJcXGmw" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=fjpAyXw2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=hqrGEgDe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=YX6VBAKj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=Hp5CWUdK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=K9PsUg6x" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=RnrDNYu4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=jAxUD6Pd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=wKAaDYbL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=3G7musxi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=EeqaLHt8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=LSXE8HU2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=GXrwmMP9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=eyVqjLS6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=7PjUJwFC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=AisgD6n3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=YRtc4Bmz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=XAqfzRSx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=M62vSew4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=MkDfQrLG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=NPrTc7ut" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=GViU5veq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=nRCAZQiy" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=uCejmG7D" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_43.lin" target="_blank">Solution</a>
Donne 44 <a href="https://bridge-training.com/player/index.php?dds=SiqTzKPB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_44.lin" target="_blank">Solution</a>
Donne 45 <a href="https://bridge-training.com/player/index.php?dds=SQBMEmkW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_45.lin" target="_blank">Solution</a>
Donne 46 <a href="https://bridge-training.com/player/index.php?dds=ErZaLjAb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_46.lin" target="_blank">Solution</a>
Donne 47 <a href="https://bridge-training.com/player/index.php?dds=f9PuGgnc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/6_-_Choix_de_la_couleur_a_exploiter/Donne_47.lin" target="_blank">Solution</a>
 
 <h2> 7 - Ordre de jeu des couleurs (43 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=FecPwzpt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=KScF9giD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=cuigtvVZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=cuigtvVZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=rApXFCt5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=FvhKzUm4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=zunJTGdB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=BsgZnWNf" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=KGMa6X7f" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=6z5amBqd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=ifZhBwsF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=eBpijma4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=UksF5Nf7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=HYcyxq8N" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=Efhzte9T" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=tfBFwb9h" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=iK9vcXtN" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=eHQBP2tD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=ZBr9sH4L" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=fcvGM8k6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=QtXfciYh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=Xs3S2pjT" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=V5haZbgJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=SKZwyni5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=BrHxqRLW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=c2EytqJX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=sYVFefhg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=hgbD2emL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=GTXNn3Mx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=hNPjq9Gn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=gUwYhEzX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=HAgNZtVM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=hF6x2tbU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=Fd7USNV6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=twBnCekm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=x9mKXJQ2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=gWdJY4VE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=Ps7KMvnV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=NB4XdSPc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=ZUpc8MvY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=u3VDvReH" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=GfLvh5sA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=6piBGb9U" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/7_-_Ordre_de_jeu_des_couleurs/Donne_43.lin" target="_blank">Solution</a>
 
<h2> 8 - Levee en passant ou contre-temps (19 donnes) </h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/8_-_Levee_en_passant_ou_contre-temps/Donne_19.lin" target="_blank">Solution</a>

<h2> 9 - Affranchissement ou impasse (4 donnes) </h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/9_-_Affranchissement_ou_impasse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/9_-_Affranchissement_ou_impasse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/9_-_Affranchissement_ou_impasse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/9_-_Affranchissement_ou_impasse/Donne_4.lin" target="_blank">Solution</a>

<h2> 10 - Impasse et affranchissement (3 donnes) </h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/10_-_Impasse_et_affranchissement/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/10_-_Impasse_et_affranchissement/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/10_-_Impasse_et_affranchissement/Donne_3.lin" target="_blank">Solution</a>

<h2> 11 - Impasse à l'entame (2 donnes) </h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/11_-_Impasse_a_l'entame/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/11_-_Impasse_a_l'entame/Donne_2.lin" target="_blank">Solution</a>

<h2> 14 -Tester la dernière couleur avant de choisir (2 donnes) </h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/12_-_Tester_la_derniere_couleur_avant_de_choisir/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/15_-_Plan_de_jeu_et_choix/12_-_Tester_la_derniere_couleur_avant_de_choisir/Donne_2.lin" target="_blank">Solution</a>

</pre>
</body>
</html>
