
<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à Sans-Atout</title>
<meta charset="UTF-8">
<title style="font-size:300%:"></title>
</head>

<body> 
Jeu avec le Mort à Sans-Atout</>

<p> <a href="../progresser.php">Retour</a>

<pre>
<h1> 14 - Remèdes contre l'adversaire dangereux  (217 donnes) </h1>

<h2> 1 - Adversaire dangereux et impasse (41 Donnes) </h2> 
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=qAHVcrzn">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=sRehrxgL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=qEAc3SPG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=GDhSmqna">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=Dk26srQV">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=bwdMFjy5">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=EvB9MdAb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=FRHQvG3X">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=2D8jQC6u">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=PtyRsV4Y">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=MBqtkLcz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=n35QKYug">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=iuUKA7HF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=6naqBZuk">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=2h4uVNnU">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=KjXqYs6c">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=iGepmwnL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=dANrt7Xz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=2faSEJNr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_19.lin">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=cmxkH54G">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_20.lin">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=DaFwiXAL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_21.lin">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=jECvr9cd">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_22.lin">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=ZXtSfkHs">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_23.lin">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=3iA7NKaR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_24.lin">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=rqhsJGTQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_25.lin">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=69N8dvAJ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_26.lin">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=rLTRWqC9">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_27.lin">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=Y5Tt23Cz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_28.lin">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=EyFJzRAP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_29.lin">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=vyuL6aEf">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_30.lin">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=CtZzPrwq">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_31.lin">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=Xc94ZGkw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_32.lin">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=jbMDpVmr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_33.lin">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=Hh8cetmb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_34.lin">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=4bA5a872">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_35.lin">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=J5pwmCSg">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_36.lin">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=yd6peWsF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_37.lin">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=zvsRZtX4">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_38.lin">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=NxjR3PEb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_39.lin">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=9euAi2NY">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_40.lin">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=gJpq2swQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/1_-_Adversaire_dangereux_et_impasse/Donne_41.lin">Solution</a>

<h2> 2 - Affranchissement orienté (19 donnes)  </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=ZfU5CsKj">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=6dAh3HtD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=iEPF2NVY">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=Mkc4TVjS">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=uxA8qvJa">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=jnxHdBEc">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=pT2w7Qmt">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=tQ2HsdEm">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=RpXkhTCu">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=nqCENvWF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=qemi4LuD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=jv6SfNpb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=yGnRgbjV">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=wW8J6Shj">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=KwYykS5V">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=P5ZhMAp2">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=NhrZQdmw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=EXdutpk3">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=E53gYMGz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/2_-_Affranchissement_oriente/Donne_19.lin">Solution</a>

<h2> 3 - Evite de l'adversaire dangereux (30 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=VEntfQzc">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=h96U2rBS">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=BZYkQdqG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=83GjfMJe">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=TjY73UtS">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=re7KpFsL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=wnJjeMUz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=2zwT3ecW">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=Yg84M2GR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=N2mqL5cs">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=Z7BHKwmu">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=nXqWZPy3">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=SnKiRkMr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=dr8ESG6Y">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=MvwniJuP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=gk6bHZpq">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=cmjGfLrD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=nrWiqcE8">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=fw5dm7TC">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_19.lin">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=ScFUHYDT">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_20.lin">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=iuUKA7HF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_21.lin">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=LeHpJ5c4">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_22.lin">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=iW9Q4TgF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_23.lin">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=h4wJftLj">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_24.lin">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=Ca7GtdgR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_25.lin">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=KtEvnBR5">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_26.lin">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=Pd9Z7Geu">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_27.lin">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=iJUGkHZB">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_28.lin">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=pYV6cwBQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_29.lin">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=Ca7GtdgR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/3_-_Evite_de_l'adversaire_dangereux/Donne_30.lin">Solution</a>

<h2> 4 - Desarmer d'abord  l'adversaire dangereux (26 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=8qgV2Mfw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=NQ4qtkCh">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=ztLTaDrH">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=5qaYpRVK">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=VmsPphcK">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=G6gqcQxa">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=HVszXYre">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=HAqBC7Dv">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=3yV8XvwD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=fVN3zUtG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=nrbqk3C9">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=cuM8xeQ5">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=AcQurPT4">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=ySZz3FpW">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=gzras5vR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=Y2AFTKRi">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=CSZuzBbh">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=JqyhM9Ej">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=QEfLPJz7">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_19.lin">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=3dGMpSgr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_20.lin">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=cmjGfLrD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_21.lin">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=6CPNrAhM">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_22.lin">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=KDEv4sfz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_23.lin">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=aju4Xs9C">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_24.lin">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=ruptBG3J">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_25.lin">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=CXjmyQBG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/4_-_Desarmer_d'abord_l'adversaire_dangereux/Donne_26.lin">Solution</a>

<h2> 5 - Le contre-temps (9 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=eWiHJy3V">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=wCtazARr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=mrnwZLSC">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=Vi7RT8Wb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=6xzH74yV">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=tLzi2hJ6">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=TvUiLV52">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=jZULqH7A">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=aApWjYEu">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/5_-_Le_contre-temps/Donne_9.lin">Solution</a>

<h2> 6 - Impasse sur l'adversaire dangereux (51 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=783wJsbm">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=k3n6zj8C">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=XhzwFc3T">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=BrChnqAT">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=dwJRzFD7">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=H59RKYLe">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=V4UKSHFG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=x8L4SUj3">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=h4X3wMD7">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_8.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=fTpJGLKn">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=29HUwjVW">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=b24MAJkp">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=rqhsJGTQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=JSxAVHb8">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=7nz5qjef">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=8AhSW7zj">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=WQNa5B36">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=FH5nqg8V">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=kTdASXb5">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_19.lin">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=WyQviKnZ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_20.lin">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=kJbedgRU">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_21.lin">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=BEDnVKfr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_22.lin">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=Mp6YKej4">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_23.lin">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=w5TXzYki">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_24.lin">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=Pvfy24LN">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_25.lin">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=MLr92ASw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_26.lin">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=gNKvsZt6">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_27.lin">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=9jVvHP3d">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_28.lin">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=frQ73zWK">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_29.lin">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=Hh8cetmb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_30.lin">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=tnAcz9NB">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_31.lin">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=smvMuDNP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_32.lin">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=quKWQEPR">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_33.lin">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=cQv47Vgx">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_34.lin">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=Ddvcgf8R">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_35.lin">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=nA4rUFgy">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_36.lin">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=PZuR6dfE">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_37.lin">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=KTtQ9bmc">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_38.lin">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=myi7KHGB">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_39.lin">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=brYnpUFw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_40.lin">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=qzmrAVcy">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_41.lin">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=3SuKdWqG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_42.lin">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=38b6gSJ7">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_43.lin">Solution</a>
Donne 44 <a href="https://bridge-training.com/player/index.php?dds=SiywPJEK">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_44.lin">Solution</a>
Donne 45 <a href="https://bridge-training.com/player/index.php?dds=gJpq2swQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_45.lin">Solution</a>
Donne 46 <a href="https://bridge-training.com/player/index.php?dds=tmJjg3Tn">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_46.lin">Solution</a>
Donne 47 <a href="https://bridge-training.com/player/index.php?dds=tTdViyYJ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_47.lin">Solution</a>
Donne 48 <a href="https://bridge-training.com/player/index.php?dds=pyqwdfsL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_48.lin">Solution</a>
Donne 49 <a href="https://bridge-training.com/player/index.php?dds=PLQHvu9i">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_49.lin">Solution</a>
Donne 50 <a href="https://bridge-training.com/player/index.php?dds=FEbC2DuT">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_50.lin">Solution</a>
Donne 51 <a href="https://bridge-training.com/player/index.php?dds=qemi4LuD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/6_-_Impasse_sur_l'adversaire_dangereux/Donne_51.lin">Solution</a>

<h2> 7 - Impasse pour empecher un retour dangereux (11 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=s7FkKAxc">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=p6ZQArg2">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=rAVh3C2c">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=whPgrWsE">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=8pEdDbQP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=gJsX8kSi">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=udj4qywP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=rqhsJGTQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=nGQtTARf">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=r6LAndh8">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=xQL47SRv">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/7_-_Impasse_pour_empecher_un_retour_dangereux/Donne_11.lin">Solution</a>

<h2> 8 - Le refus d'impasse (11 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=3ViyuNA6">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=jRn24zyw">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=MWki4YcP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=ARynTQVL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=dxWRPzM3">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=VQAv7hHx">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=PdB7GM8n">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=zjvRriKB">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=2ZFTwS7K">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=ruptBG3J">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=9KTJZD5r">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/8_-_Le_refus_d'impasse/Donne_11.lin">Solution</a>

<h2> 9 - Elimination et remise en main (12 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=tjPxWnaL">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=EmPYCdbz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=LhxJVNZF">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=nzuDUxeq">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=7WvAicL2">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=T4Zgpytr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=E6rX8LsW">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=NnFgBrLt">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=McHqZvCa">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_9.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=MC8vi7yt">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=NfVvt6sD">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=uHq75AkU">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/9_-_Elimination_et_remise_en_main/Donne_12.lin">Solution</a29

<h2> 10 - Le baiser à la reine (29 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=mtzVWsHu">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=nMqNG6Kh">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=ckTywE6L">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=782kuz3d">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=EXcdvq7t">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=rNMHxXu5">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=kFPXvmY4">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_7.lin">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=sbVPuYfz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_8.lin">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=gJsuBHUz">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_8.lin">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=qLU4RrgE">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_10.lin">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=9xB3auCh">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_11.lin">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=A95ywpqr">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_12.lin">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=nSw2vC7r">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_13.lin">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=xTBmRc76">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_14.lin">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=NJhLTw6G">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_15.lin">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=kV6RMGaP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_16.lin">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=zk4YGNar">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_17.lin">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=EfgtFTVn">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_18.lin">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=Vv2p9UjN">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_19.lin">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=SyqVurmC">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_20.lin">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=jmsnaBEG">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_21.lin">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=8RbuptDQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_22.lin">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=ZB6RFtsH">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_23.lin">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=6M4vpJBN">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_24.lin">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=wtueZQfv">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_25.lin">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=SyqVurmC">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_26.lin">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=q4ufdDrM">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_27.lin">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=uBKWxe6a">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_28.lin">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=YSedN7kb">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/10_-_Le_baiser_a_la_reine/Donne_29.lin">Solution</a>

<h2> 11 - Le baiser au roi (7 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=wdLQ3NuZ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=FxPX3peq">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=4r7yX9RW">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_3.lin">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=Qy36RzPV">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_4.lin">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=9VBdUXqt">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_5.lin">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=4m6hweNQ">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_6.lin">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=fuwN2q7B">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/11_-_Le_baiser_au_roi/Donne_7.lin">Solution</a>

<h2> 12 - Le baiser au valet (3 donnes) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=LtGwaX3W">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/12_-_Le_baiser_au_valet/Donne_1.lin">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=vpMkQmSC">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/12_-_Le_baiser_au_valet/Donne_2.lin">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=Lq4EXKDj">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/12_-_Le_baiser_au_valet/Donne_3.lin">Solution</a>

<h2> 13 - Baiser inversé (1 donne) </h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=2tnFaXZP">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMSA/14_-_Remedes_contre_l'adversaire_dangereux/13_-_Baiser_inverse/Donne_1.lin">Solution</a

</pre>
</body>
</html>
