

<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à l'atout</title>
<meta charset="UTF-8">
<title style="font-size:300%;"></title>
</head>

<body> 
Jeu avec le Mort à l'atout

<p> <a href="../debutant.php">Retour</a>

<pre>
<h1>Coupe(s) immédiate(s) de la main coutes </h1>

<h2> <a href="https://docs.google.com/presentation/d/1Ka0wWatLpj0wra2kELOvqBwuPRiBG2SjAr3QlSX0Ycg/edit?slide=id.p1#slide=id.p1">Cours Coupes immédiates de la main courte</h2>

<h2>1 -  Une coupe de la main courte</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=bqEwMVrd" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=f8Lp2mbQ" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=8zSWaPf7" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=WVHC4dBt" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=dXDEimYj" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 6 <a href="https://bridge-training.com/player?dds=dXDEimYj" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_6.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 7 <a href="https://bridge-training.com/player?dds=h3imMRfJ" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_7.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 8 <a href="https://bridge-training.com/player?dds=wD2dh3np" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_8.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 9 <a href="https://bridge-training.com/player?dds=HjhXNREp" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_9.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 10 <a href="https://bridge-training.com/player?dds=kVt53fZ2" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_10.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 11 <a href="https://bridge-training.com/player?dds=sUBaWY2i" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_11.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 12 <a href="https://bridge-training.com/player?dds=LZQEjXsY" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_12.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 13 <a href="https://bridge-training.com/player?dds=rKqnQauZ" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_13.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 14 <a href="https://bridge-training.com/player?dds=KhSXntdu" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_14.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 15 <a href="https://bridge-training.com/player?dds=T8ycfxGP" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_15.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 16 <a href="https://bridge-training.com/player?dds=SMGEmnP9" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_16.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 17 <a href="https://bridge-training.com/player?dds=CbXhtTnK" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_17.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 18 <a href="https://bridge-training.com/player?dds=ZVnPayRF" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_18.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 19 <a href="https://bridge-training.com/player?dds=dTfpbhL8" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/1_-_Une_coupe_de_la_main_courte/Donne_19.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>2 - Deux coupes de la main courte</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=6ZkhjeC8" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=7gdw2m6k" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=QGTwipKv" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=BYVKfcJ7" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=ENLjVmYe" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 6 <a href="https://bridge-training.com/player?dds=5KCSwuXm" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_6.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 7 <a href="https://bridge-training.com/player?dds=dwFpLm42" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_7.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 8 <a href="https://bridge-training.com/player?dds=HzGFJ49r" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_8.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 9 <a href="https://bridge-training.com/player?dds=gUGVNQh5" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_9.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 10 <a href="https://bridge-training.com/player?dds=qdDk35gj" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_10.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 11 <a href="https://bridge-training.com/player?dds=4BNUvMz3" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_11.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 12 <a href="https://bridge-training.com/player?dds=aMqpLTcX" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_12.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 13 <a href="https://bridge-training.com/player?dds=MFCiEHzn" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_13.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 14 <a href="https://bridge-training.com/player?dds=CcLsh6Yt" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_14.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 15 <a href="https://bridge-training.com/player?dds=ugsEraqU" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_15.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 16 <a href="https://bridge-training.com/player?dds=7AyNHFQU" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_16.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 17 <a href="https://bridge-training.com/player?dds=ASFRdpLk" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_17.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 18 <a href="https://bridge-training.com/player?dds=meh7Anu5" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_18.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 19 <a href="https://bridge-training.com/player?dds=bPzLnrka" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_19.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 20 <a href="https://bridge-training.com/player?dds=5QaqWvXT" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_20.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 21 <a href="https://bridge-training.com/player?dds=UCeT5SXf" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_21.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 22 <a href="https://bridge-training.com/player?dds=hs4evzEn" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_22.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 23 <a href="https://bridge-training.com/player?dds=ELN2kzZM" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_23.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 24 <a href="https://bridge-training.com/player?dds=THDsmZ4v" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_24.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 25 <a href="https://bridge-training.com/player?dds=38iCYZqF" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_25.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 26 <a href="https://bridge-training.com/player?dds=eZa9gvn5" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/2_-_2_coupes_de_la_main_courte/Donne_26.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>3 - Trois coupes de la main courte</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=jBTaSdVM" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/3_-_3_coupes_de_la_main_courte/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=DsvE49HK" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/3_-_3_coupes_de_la_main_courte/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=rL69tfyY" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/3_-_3_coupes_de_la_main_courte/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=gURzbVsw" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/3_-_3_coupes_de_la_main_courte/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=YjBmKxhw" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/13_-_Coupe(s)_immediate(s)_de_la_main_courte/3_-_3_coupes_de_la_main_courte/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
</pre>
</body>
</html>
