

<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à l'atout</title>
<meta charset="UTF-8">
<title style="font-size:300%;"></title>
</head>

<body> 
Jeu avec le Mort à l'atout

<p> <a href="../debutant.php">Retour</a>

<pre>
<h1>Réalisation de levées quasi-immédiates</h1>

<a href="https://docs.google.com/presentation/d/1fRz635K9WxnsbVle9Eec9D1oLHcERy_OWYYURBDIsjg/edit?slide=id.p1#slide=id.p1">Cours levées quasi-immédiates

<h2>1 - Compte des levées gagnantes</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=xTZHijSF" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=GUjDYEQx" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=XFmVe2th" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=Jzj62sRN" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=uHjFbYDx" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 6 <a href="https://bridge-training.com/player?dds=q6put7k3" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_6.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 7 <a href="https://bridge-training.com/player?dds=wkTDPJGv" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_7.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 8 <a href="https://bridge-training.com/player?dds=LcDjmMpz" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_8.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 9 <a href="https://bridge-training.com/player?dds=wsNr9euJ" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_9.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 10 <a href="https://bridge-training.com/player?dds=gqRU7kZt" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_10.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 11 <a href="https://bridge-training.com/player?dds=cy7vfTug" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_11.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 12 <a href="https://bridge-training.com/player?dds=6nSx3zg5" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_12.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 13 <a href="https://bridge-training.com/player?dds=sRGQ6aB4" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_13.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 14 <a href="https://bridge-training.com/player?dds=WjP34TLE" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_14.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 15 <a href="https://bridge-training.com/player?dds=g7uB8YHz" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_15.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 16 <a href="https://bridge-training.com/player?dds=Uud6cmeH" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_16.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 17 <a href="https://bridge-training.com/player?dds=QBtMjv3i" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_17.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 18 <a href="https://bridge-training.com/player?dds=HwqU7Qv3" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_18.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 19 <a href="https://bridge-training.com/player?dds=qEzSbBL8" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_19.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 20 <a href="https://bridge-training.com/player?dds=M7APFgti" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_20.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 21 <a href="https://bridge-training.com/player?dds=f3vkQxmh" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_21.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 22 <a href="https://bridge-training.com/player?dds=2FucCRpe" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_22.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 23 <a href="https://bridge-training.com/player?dds=W4EA6vra" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_23.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 24 <a href="https://bridge-training.com/player?dds=Ycw3BP9J" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_24.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 25 <a href="https://bridge-training.com/player?dds=BejRDCiY" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_25.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 26 <a href="https://bridge-training.com/player?dds=3B6jwAsi" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_26.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 27 <a href="https://bridge-training.com/player?dds=4gskcpQ6" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_27.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 28 <a href="https://bridge-training.com/player?dds=CUnRDVmu" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_28.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 29 <a href="https://bridge-training.com/player?dds=AgDqLB8u" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_29.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 30 <a href="https://bridge-training.com/player?dds=rdAD3zyL" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/1_-_Compte_des_levees_gagnantes/Donne_30.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>2 - Compte des perdantes</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=C9bM2XVc" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=krGT2J3A" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=bmGSM8AV" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=25BKNvCW" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=bi2SL8kn" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 6 <a href="https://bridge-training.com/player?dds=3dSG7Qsw" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_6.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 7 <a href="https://bridge-training.com/player?dds=KXVkwE4r" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_7.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 8 <a href="https://bridge-training.com/player?dds=4jJyvf6g" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_8.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>3 - Affranchissement de levées d'honneurs</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=xXFCkwdY" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=kKHiZVA9" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=yjXbfR9A" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 4 <a href="https://bridge-training.com/player?dds=rsYNVQKv" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_4.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 5 <a href="https://bridge-training.com/player?dds=" target="_blank">Jouer avec Bridge Training <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_5.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 6 <a href="https://bridge-training.com/player?dds=vyTVCzac" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_6.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 7 <a href="https://bridge-training.com/player?dds=6DwARxzr" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/3_-_Affranchissement_de_levees_d'honneurs/Donne_7.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>4 - Faire tomber les atouts pour empecher de les dédoubler</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=rVj6tk9R" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/4_-_Faire_tomber_les_atouts_pour_empecher_de_les_dedoubler/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=pB8YTtbF" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/4_-_Faire_tomber_les_atouts_pour_empecher_de_les_dedoubler/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>

<h2>5 - Impasse obligatoire</h2>
Donne 1 <a href="https://bridge-training.com/player?dds=AZEftkwD" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/5_-_Impasse_obligatoire/Donne_1.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 2 <a href="https://bridge-training.com/player?dds=YiZ4ShEP" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/5_-_Impasse_obligatoire/Donne_2.lin" target="_blank">Solution avec  Bridge Solver</a>
Donne 3 <a href="https://bridge-training.com/player?dds=sLn5akPG" target="_blank">Jouer avec Bridge Training  <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMA/12_-_Realisation_des_levees_quasi-immediates/5_-_Impasse_obligatoire/Donne_3.lin" target="_blank">Solution avec  Bridge Solver</a>
</pre>
</body>
</html>
