

<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à l'atout</title>
<meta charset="UTF-8">
<title style="font-size:300%;"></title>
</head>

<body> 
Jeu avec le Mort à l'atout

<p> <a href="../progresser.php">Retour</a>

<pre>
<h1>5 - Affranchissement d'une couleur du Mort (160 donnes)</h1>
<h2>1 - Affranchissement d'honneurs (59 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=F7TPuMSc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=Vvck3hXE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=hnwMsyVK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=GsETvXUp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=7CW8bt9E" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=HrN4CJzD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=zYPdVyZm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=3BWbK8ie" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=JhBbFwpS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=nqPAZFiy" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=xY7bJQFA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=Js3ykUde" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=D5QYVdjv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=jBfb5Dkc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=82ZmgrEx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=KvkWDCUE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=J539tvbx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=uN2RJgfF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=wn8zUJvi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=Pdjxyahm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=CGBZJLki" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=QBcSKDrj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=jQdrunBT" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=MuwPqAtg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=KuhXgPWF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=9QRi53kY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=9QRi53kY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=PsLuMf8m" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=Adag2JbE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=CJgBnkQM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=4F7w2uNe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=rHzMUgPs" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=cFqTeHjJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=YmAf5ecz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=nzMRBQPm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=bdTF2JeV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=6NYfcpJK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=CKzetavc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=37EBAw5x" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_38.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=rDd9cVKM" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=cmBYkULv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=xV75szXi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=4xjgAQsS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_43.lin" target="_blank">Solution</a>
Donne 44 <a href="https://bridge-training.com/player/index.php?dds=EtzjL965" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_44.lin" target="_blank">Solution</a>
Donne 45 <a href="https://bridge-training.com/player/index.php?dds=56WdpYNX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_45.lin" target="_blank">Solution</a>
Donne 46 <a href="https://bridge-training.com/player/index.php?dds=kWVNzvXh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_46.lin" target="_blank">Solution</a>
Donne 47 <a href="https://bridge-training.com/player/index.php?dds=cpzS7Lve" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_47.lin" target="_blank">Solution</a>
Donne 48 <a href="https://bridge-training.com/player/index.php?dds=cXS3kKGZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_48.lin" target="_blank">Solution</a>
Donne 49 <a href="https://bridge-training.com/player/index.php?dds=behLNrix" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_49.lin" target="_blank">Solution</a>
Donne 50 <a href="https://bridge-training.com/player/index.php?dds=4GMHP7UZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_50.lin" target="_blank">Solution</a>
Donne 51 <a href="https://bridge-training.com/player/index.php?dds=J539tvbx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_51.lin" target="_blank">Solution</a>
Donne 52 <a href="https://bridge-training.com/player/index.php?dds=GcMDPhZY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_52.lin" target="_blank">Solution</a>
Donne 53 <a href="https://bridge-training.com/player/index.php?dds=cgqNPEBp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_53.lin" target="_blank">Solution</a>
Donne 54 <a href="https://bridge-training.com/player/index.php?dds=wercYKQE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_54.lin" target="_blank">Solution</a>
Donne 55 <a href="https://bridge-training.com/player/index.php?dds=BmvxwEZP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_55.lin" target="_blank">Solution</a>
Donne 56 <a href="https://bridge-training.com/player/index.php?dds=n3G9weAU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_55.lin" target="_blank">Solution</a>
Donne 57 <a href="https://bridge-training.com/player/index.php?dds=MaKGjm6Q" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_56.lin" target="_blank">Solution</a>
Donne 58 <a href="https://bridge-training.com/player/index.php?dds=2BLkDSNY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_58.lin" target="_blank">Solution</a>
Donne 59 <a href="https://bridge-training.com/player/index.php?dds=Y9Z6F4St" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/1_-_Affranchissement_d'honneurs/Donne_59.lin" target="_blank">Solution</a>

<h2>2 - Affranchissement d'une longue du mort par la coupe (50 donnes)</h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_43.lin" target="_blank">Solution</a>
Donne 44 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_44.lin" target="_blank">Solution</a>
Donne 45 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_45.lin" target="_blank">Solution</a>
Donne 46 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_46.lin" target="_blank">Solution</a>
Donne 47 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_47.lin" target="_blank">Solution</a>
Donne 48 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_48.lin" target="_blank">Solution</a>
Donne 49 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_49.lin" target="_blank">Solution</a>
Donne 50 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/2_-_Affranchissement_d'une_longue_du_mort_par_la_coupe/Donne_50.lin" target="_blank">Solution</a>

<h2>3 -Affranchissement d'un honneur par la coupe (10 donnes)</h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/3_-_Affranchissement_d'un_honneur_par_la_coupe/Donne_10.lin" target="_blank">Solution</a>

<h2>4 - Affranchissement par un coup à blanc (22 donnes)</h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/4_-_Affranchissement_par_un_coup_a_blanc/Donne_22.lin" target="_blank">Solution</a>

<h2>5 - Affrancchissement par l'impasse ou l' expasse (19 donnes)</h2>
Donne 1 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/24_-_Affranchissement_d'une_couleur_du_Mort/5_-_Affranchissement_par_l'impasse_ou_l'expasse/Donne_18.lin" target="_blank">Solution</a>

</pre>
</body>
</html>
