

<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à l'atout</title>
<meta charset="UTF-8">
<title style="font-size:300%;"></title>
</head>

<body> 
Jeu avec le Mort à l'atout

<p> <a href="../progresser.php">Retour</a>

<pre>
<h1>7 - La Défausse des perdantes (donnes)</h1>

<h2>1 - Utiliser ou créer une extra-gagnante pour défausser (72 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=eTcC7AiV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=sbcwn9ik" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=qy7erEzd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=YPRtKUwB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=Hym4baAg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=XnJwBhsZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=yur74UwJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=Pgks2jrq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=cPVKEszb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=aCskqZQA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=5MjnPNtR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=8GMDmKZ5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=3cxqywhv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=p5cDuRJq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=FuaeAnVD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=5PBEQ9df" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=UaJvxnQ2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=5vMGRkVa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=TaYpu2MP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=VuYDUQrg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=Wsz2LPXQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=3xLzG2Xp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=C7sAPzSE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=L5csrGZe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=KJiyem7k" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=umrFJ4Si" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=TeMiuJ95" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=nwJCTPbD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=qvrnm7i8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=WuvbwEkN" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=FV3fex6W" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=R9cTQ7Fg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=RTz2MUWX" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=832iTGAS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=VxUPpS7R" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=TuedzK5j" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=iwCbkHTt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=AXRbgdfv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=2dRgJv3F" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=QMBnhqkL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=tQwV5mgq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=kGnHU3wg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=rZmG26U8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_43.lin" target="_blank">Solution</a>
Donne 44 <a href="https://bridge-training.com/player/index.php?dds=bZkcJ3H5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_44.lin" target="_blank">Solution</a>
Donne 45 <a href="https://bridge-training.com/player/index.php?dds=xGqCbs6m" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_45.lin" target="_blank">Solution</a>
Donne 46 <a href="https://bridge-training.com/player/index.php?dds=anz2AsqC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_46.lin" target="_blank">Solution</a>
Donne 47 <a href="https://bridge-training.com/player/index.php?dds=zSfj8L9C" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_47.lin" target="_blank">Solution</a>
Donne 48 <a href="https://bridge-training.com/player/index.php?dds=yur74UwJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_48.lin" target="_blank">Solution</a>
Donne 49 <a href="https://bridge-training.com/player/index.php?dds=HpE5mNie" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_49.lin" target="_blank">Solution</a>
Donne 50 <a href="https://bridge-training.com/player/index.php?dds=DCbakp63" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_50.lin" target="_blank">Solution</a>
Donne 51 <a href="https://bridge-training.com/player/index.php?dds=CJvc3YwQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_51.lin" target="_blank">Solution</a>
Donne 52 <a href="https://bridge-training.com/player/index.php?dds=G9mRjaU3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_52.lin" target="_blank">Solution</a>
Donne 53 <a href="https://bridge-training.com/player/index.php?dds=gta6mJ7V" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_53.lin" target="_blank">Solution</a>
Donne 54 <a href="https://bridge-training.com/player/index.php?dds=suXf49DC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_54.lin" target="_blank">Solution</a>
Donne 55 <a href="https://bridge-training.com/player/index.php?dds=nZ9Uschz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_55.lin" target="_blank">Solution</a>
Donne 56 <a href="https://bridge-training.com/player/index.php?dds=W5Fai2sK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_56.lin" target="_blank">Solution</a>
Donne 57 <a href="https://bridge-training.com/player/index.php?dds=pqjU7m3n" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_57.lin" target="_blank">Solution</a>
Donne 58 <a href="https://bridge-training.com/player/index.php?dds=5XxGvApC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_58.lin" target="_blank">Solution</a>
Donne 59 <a href="https://bridge-training.com/player/index.php?dds=reiREcfP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_59.lin" target="_blank">Solution</a>
Donne 60 <a href="https://bridge-training.com/player/index.php?dds=S3zftUa5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_60.lin" target="_blank">Solution</a>
Donne 61 <a href="https://bridge-training.com/player/index.php?dds=jeM4LZrU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_61.lin" target="_blank">Solution</a>
Donne 62 <a href="https://bridge-training.com/player/index.php?dds=zfEvDKGh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_62.lin" target="_blank">Solution</a>
Donne 63 <a href="https://bridge-training.com/player/index.php?dds=tXzKMWhc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_63.lin" target="_blank">Solution</a>
Donne 64 <a href="https://bridge-training.com/player/index.php?dds=M9cXZhpe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_64.lin" target="_blank">Solution</a>
Donne 65 <a href="https://bridge-training.com/player/index.php?dds=sM7BRbKj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_65.lin" target="_blank">Solution</a>
Donne 66 <a href="https://bridge-training.com/player/index.php?dds=PXy2dYCz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_66.lin" target="_blank">Solution</a>
Donne 67 <a href="https://bridge-training.com/player/index.php?dds=ht7qknQJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_67.lin" target="_blank">Solution</a>
Donne 68 <a href="https://bridge-training.com/player/index.php?dds=AiaDxYdS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_68.lin" target="_blank">Solution</a>
Donne 69 <a href="https://bridge-training.com/player/index.php?dds=6DUjiRv3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_69.lin" target="_blank">Solution</a>
Donne 70 <a href="https://bridge-training.com/player/index.php?dds=gu7bB3Ep" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_70.lin" target="_blank">Solution</a>
Donne 71 <a href="https://bridge-training.com/player/index.php?dds=xK9DSRYw" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_71.lin" target="_blank">Solution</a>
Donne 72 <a href="https://bridge-training.com/player/index.php?dds=GfWM2pa8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/1_-_Utiliser_ou_creer_une_extra-gagnante_pour_défausser/Donne_72.lin" target="_blank">Solution</a>
D
<h2>2 - Retrait de tous les  atouts avant défausse (23 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=rKbnW5cq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=zpM8iHjF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=qeP7Q4KE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=CGi9Symu" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=9fBkKc2L" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=6ucNF8Mf" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=g7e4fXz3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=LP538vNr" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=pjJPqsin" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=M9cXZhpe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=9UN2RHX5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=WSCHGxuZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=QJXzBRaG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=eyTxKiVL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=CPwgdzxF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=AZsJcgYt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=qUABgHCJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=xjyaZNzv" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=rF4wmVP7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=PQ8XGSNC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=HrRgNapA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=envDUhRC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=6U4DVycW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/2_-_Retrait_de_tous_les_atouts_avant_defausse/Donne_1usse/Donne_23.lin" target="_blank">Solution</a>

<h2>3 - Retrait partiel des atouts avant défausse (20 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=uyP4srMi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=ckHKp9qJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=nayVHN2S" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=KA32iCrx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=Gd6FSYap" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=Ue9kPK4c" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=xpH2v9Pd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=Hft8zZBA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=6KJWi9cw" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=diFKxEea" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=bcdafKA8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=ip7f3Utz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=dpBb48hG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=df3PVMTq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=v5CjHzTp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=LipjgtRa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=3BX2Kstz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=s5GpBYXz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=TLgWMuN7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=qW3XRgNk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/3_-_Retrait_partiel_des_atouts_avant_defausse/Donne_20.lin" target="_blank">Solution</a>

<h2>4 - Affranchissement immédiat pour défausser une perdante (39 dfonnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=4GMHP7UZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=DUYtwuyR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=znVaHKcS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=gyRT8CY4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=J539tvbx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=pcTiqjg4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=akT5KxH2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=anz2AsqC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=emfTaS5q" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=UdRJACzu" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=QYXdftzK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=VD9kiPsb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=ih54WFMV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=nkRfZaPH" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=KfpcekRW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=MWenKxqE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=6DUjiRv3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=TiP3Dr6v" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=MJsLWPpt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=kLDXSUCt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=fUrB4bvt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=HKxgsjPY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=ngzHPZG6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=tu6ZH9BL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=nYvyS9Lh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=7u4snpa9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=uJFp2BYQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=xeHUzBLP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=ZyUDQnkq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=LX9pzA8K" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=mk5LXY7E" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=zfEvDKGh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=MS72YKPD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=TcUnJVdQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=BW39AnN6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=nSqH8z2R" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=hV3T9JqR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=5kQfDRxt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=RSj5MvVe" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/4_-_Affranchissement_immediat_pour_defausser_une_perdante/Donne_39.lin" target="_blank">Solution</a>

<h2>5 - Impasse-expasse pour une défausse urgente (56 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=UkQsvfjx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=dXznTpMk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=ZiG8muJY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=6msvT7ya" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=6uxAU9ma" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=X4TjuZBm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=uRkW4bNj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=NRXmFVdU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=DUYtwuyR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=eZSwEmV4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=V8Nuag5i" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=KeVPHzUE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=Lps4wSKk" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=aDGZujgQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=VzrTZ5Rc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=N6Kn4qmg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=XyWTs6Kz" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=mSDFKGXd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=q6dT2fms" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=jfrq8cYE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=SgjZYW64" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=fkp93rEL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=fxtRbswU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=iBZJME4n" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=fq3z6UeZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=Rxt9gdZ4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=dBh3kPLg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=rPiWR93m" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=MvhiZBA3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=mjzxuwi5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=W9cdUtmn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=9mnaN8uY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=x9hdJ4jw" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=sFvit8Dj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=ApRqXLzf" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=SgM3Tkhj" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=vsFzMwrC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=TNpijDSY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=WGQBy8pS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=uzpL3qFi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_40.lin" target="_blank">Solution</a>
Donne 41 <a href="https://bridge-training.com/player/index.php?dds=STcNribY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_41.lin" target="_blank">Solution</a>
Donne 42 <a href="https://bridge-training.com/player/index.php?dds=FnkLArV6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_42.lin" target="_blank">Solution</a>
Donne 43 <a href="https://bridge-training.com/player/index.php?dds=n8cmiSYP" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_43.lin" target="_blank">Solution</a>
Donne 44 <a href="https://bridge-training.com/player/index.php?dds=Jqc79PAg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_44.lin" target="_blank">Solution</a>
Donne 45 <a href="https://bridge-training.com/player/index.php?dds=WGQBy8pS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_45.lin" target="_blank">Solution</a>
Donne 46 <a href="https://bridge-training.com/player/index.php?dds=3r8CbNhd" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_46.lin" target="_blank">Solution</a>
Donne 47 <a href="https://bridge-training.com/player/index.php?dds=C2ic7z45" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_47.lin" target="_blank">Solution</a>
Donne 48 <a href="https://bridge-training.com/player/index.php?dds=5Xb2QPSZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_48.lin" target="_blank">Solution</a>
Donne 49 <a href="https://bridge-training.com/player/index.php?dds=jS6tF4xG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_49.lin" target="_blank">Solution</a>
Donne 50 <a href="https://bridge-training.com/player/index.php?dds=VMBmi3Zx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_50.lin" target="_blank">Solution</a>
Donne 51 <a href="https://bridge-training.com/player/index.php?dds=pSkYH6nc" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_51.lin" target="_blank">Solution</a>
Donne 52 <a href="https://bridge-training.com/player/index.php?dds=EDnxTq2b" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_52.lin" target="_blank">Solution</a>
Donne 53 <a href="https://bridge-training.com/player/index.php?dds=KWFRDhM8" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_53.lin" target="_blank">Solution</a>
Donne 54 <a href="https://bridge-training.com/player/index.php?dds=DUYtwuyR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_54.lin" target="_blank">Solution</a>
Donne 55 <a href="https://bridge-training.com/player/index.php?dds=AWSpMcT7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_55.lin" target="_blank">Solution</a>
Donne 56 <a href="https://bridge-training.com/player/index.php?dds=J2TnNRuD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/5_-_Impasse-expasse_pour_une_defausse_urgente/Donne_56.lin" target="_blank">Solution</a>


<h2>6 - Réaliser une possibilité de défausse dès l'entame (4 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=KFVLGkDS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/6_-_Realiser_une_possibilité_de_defausse_des_l'entame/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=9QwVkKzG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/6_-_Realiser_une_possibilité_de_defausse_des_l'entame/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=CPWex3T2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/6_-_Realiser_une_possibilité_de_defausse_des_l'entame/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=Sax6cX8H" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/26_-_La_defausse_des_perdantes/6_-_Realiser_une_possibilité_de_defausse_des_l'entame/Donne_4.lin" target="_blank">Solution</a>

</pre>
</body>
</html>
