

<!DOCTYPE html>
<html> 

<head>
<title>Jeu avec le Mort à l'atout</title>
<meta charset="UTF-8">
<title style="font-size:300%;"></title>
</head>

<body> 
Jeu avec le Mort à l'atout

<p> <a href="../progresser.php">Retour</a>

<pre>
<h1>6 - Affranchissement d'une couleur secondaire (donnes)</h1>

<h2>1 -  Par la coupe (41 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=cyA254Si" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=h3Sey4x9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=iLqsYjpy" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=k4KhYwEx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=VugGcW5n" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=WiJc4qxU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=VPN3U8H2" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=kFRj2umq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=Qc29AmWp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=qrAxNCZm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=4aQ8j2PY" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=yUunLW7F" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=i2cshvef" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=iauCP2ew" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=cHNshGqx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=KbUu8Pgh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=YJDkNCTS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=3S8YtxFR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_18.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=3S8YtxFR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_19.lin" target="_blank">Solution</a>
Donne 19 <a href="https://bridge-training.com/player/index.php?dds=SeZUFtCR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_19.lin" target="_blank">Solution</a>
Donne 20 <a href="https://bridge-training.com/player/index.php?dds=jQnBXb4V" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_20.lin" target="_blank">Solution</a>
Donne 21 <a href="https://bridge-training.com/player/index.php?dds=3VEHmzYf" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_21.lin" target="_blank">Solution</a>
Donne 22 <a href="https://bridge-training.com/player/index.php?dds=NZmiAdWB" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_22.lin" target="_blank">Solution</a>
Donne 23 <a href="https://bridge-training.com/player/index.php?dds=wfzQjgyF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_23.lin" target="_blank">Solution</a>
Donne 24 <a href="https://bridge-training.com/player/index.php?dds=7pqrsmwb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_24.lin" target="_blank">Solution</a>
Donne 25 <a href="https://bridge-training.com/player/index.php?dds=2CSzL6gt" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_25.lin" target="_blank">Solution</a>
Donne 26 <a href="https://bridge-training.com/player/index.php?dds=7PwkbVn4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_26.lin" target="_blank">Solution</a>
Donne 27 <a href="https://bridge-training.com/player/index.php?dds=E4uaF7U3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_27.lin" target="_blank">Solution</a>
Donne 28 <a href="https://bridge-training.com/player/index.php?dds=vPVwHNSa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_28.lin" target="_blank">Solution</a>
Donne 29 <a href="https://bridge-training.com/player/index.php?dds=kVdpSyDa" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_29.lin" target="_blank">Solution</a>
Donne 30 <a href="https://bridge-training.com/player/index.php?dds=kp6Ux3V7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_30.lin" target="_blank">Solution</a>
Donne 31 <a href="https://bridge-training.com/player/index.php?dds=TLHw2BRC" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_31.lin" target="_blank">Solution</a>
Donne 32 <a href="https://bridge-training.com/player/index.php?dds=Wv7xeufq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_32.lin" target="_blank">Solution</a>
Donne 33 <a href="https://bridge-training.com/player/index.php?dds=MhTYRiGb" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_33.lin" target="_blank">Solution</a>
Donne 34 <a href="https://bridge-training.com/player/index.php?dds=A9BFP8xR" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_34.lin" target="_blank">Solution</a>
Donne 35 <a href="https://bridge-training.com/player/index.php?dds=xraMJgGZ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_35.lin" target="_blank">Solution</a>
Donne 36 <a href="https://bridge-training.com/player/index.php?dds=LgM46fUJ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_36.lin" target="_blank">Solution</a>
Donne 37 <a href="https://bridge-training.com/player/index.php?dds=sAMKteSi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_37.lin" target="_blank">Solution</a>
Donne 38 <a href="https://bridge-training.com/player/index.php?dds=6WpnYqAH" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_38.lin" target="_blank">Solution</a>
Donne 39 <a href="https://bridge-training.com/player/index.php?dds=xU5mR2rq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_39.lin" target="_blank">Solution</a>
Donne 40 <a href="https://bridge-training.com/player/index.php?dds=hSnsAT5x" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/1_-_Par_la_coupe/Donne_40.lin" target="_blank">Solution</a>

<h2>2 - Etablir la couleur secondaire (18 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=VYkQNMxG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=xsUyPZk6" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=AQVKy6rW" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=FLQCtzjV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=Yvbjt2Ff" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=WxYipA57" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=FVJE5tkx" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=FV3fex6W" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=frVyCkLn" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=X4VhmEkF" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_10.lin" target="_blank">Solution</a>
Donne 11 <a href="https://bridge-training.com/player/index.php?dds=DzQPBEKh" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_11.lin" target="_blank">Solution</a>
Donne 12 <a href="https://bridge-training.com/player/index.php?dds=6DUjiRv3" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_12.lin" target="_blank">Solution</a>
Donne 13 <a href="https://bridge-training.com/player/index.php?dds=9UVe4b7M" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_13.lin" target="_blank">Solution</a>
Donne 14 <a href="https://bridge-training.com/player/index.php?dds=GM6C2x7L" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_14.lin" target="_blank">Solution</a>
Donne 15 <a href="https://bridge-training.com/player/index.php?dds=jUnr8MfS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_15.lin" target="_blank">Solution</a>
Donne 16 <a href="https://bridge-training.com/player/index.php?dds=REtnPwrU" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_16.lin" target="_blank">Solution</a>
Donne 17 <a href="https://bridge-training.com/player/index.php?dds=subcURv9" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_17.lin" target="_blank">Solution</a>
Donne 18 <a href="https://bridge-training.com/player/index.php?dds=PGk7wCdq" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/2_-_Etablir_la_couleur_secondaire/Donne_18.lin" target="_blank">Solution</a>

<h2>3 -3 - Par un coup à blanc (6 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=5Nqdzyg7" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=CFsQbcx5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=QiLvraVN" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=XNFceEPV" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=6QYwKunp" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=CKLeXcaS" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/3_-_Par_un_coup_a_blanc/Donne_6.lin" target="_blank">Solution</a>

<h2>4 - Par la perte d'une levée (10 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=5BgFXCzA" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=ZnSJgH4x" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=uvEX6fYD" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=gBkUaF8j" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=bgynNXpQ" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_5.lin" target="_blank">Solution</a>
Donne 6 <a href="https://bridge-training.com/player/index.php?dds=RQf6mCS4" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_6.lin" target="_blank">Solution</a>
Donne 7 <a href="https://bridge-training.com/player/index.php?dds=z6NRdQbL" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_7.lin" target="_blank">Solution</a>
Donne 8 <a href="https://bridge-training.com/player/index.php?dds=ymZuTdpK" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_8.lin" target="_blank">Solution</a>
Donne 9 <a href="https://bridge-training.com/player/index.php?dds=4tJzFNr5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_9.lin" target="_blank">Solution</a>
Donne 10 <a href="https://bridge-training.com/player/index.php?dds=KyPkW2E5" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/4_-_Par_la_perte_d'une_levee/Donne_10.lin" target="_blank">Solution</a>

<h2>5 - Par l'impasse ((5 donnes)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=azgcEL6J" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/5_-_Par_l'impasse/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=bSWZDGPi" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/5_-_Par_l'impasse/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=DSzTe8Gm" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/5_-_Par_l'impasse/Donne_3.lin" target="_blank">Solution</a>
Donne 4 <a href="https://bridge-training.com/player/index.php?dds=Mm4qBwAu" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/5_-_Par_l'impasse/Donne_4.lin" target="_blank">Solution</a>
Donne 5 <a href="https://bridge-training.com/player/index.php?dds=VYkQNMxG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/5_-_Par_l'impasse/Donne_5.lin" target="_blank">Solution</a>

<h2> 6 - Par la defausse d'une perdante (3 levées)</h2>
Donne 1 <a href="https://bridge-training.com/player/index.php?dds=6PtrGvWg" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/6_-_Par_la_defausse_d'une_perdante/Donne_1.lin" target="_blank">Solution</a>
Donne 2 <a href="https://bridge-training.com/player/index.php?dds=j4itKADE" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/6_-_Par_la_defausse_d'une_perdante/Donne_2.lin" target="_blank">Solution</a>
Donne 3 <a href="https://bridge-training.com/player/index.php?dds=jS6tF4xG" target="_blank">Jouer / <a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Progresser/JMA/25_-_Affranchissement_d'une_couleur_secondaire/6_-_Par_la_defausse_d'une_perdante/Donne_3.lin" target="_blank">Solution</a>

</pre>
</body>
</html>
