<?php
include '../../../includes/header.php'; ?>
<link rel="stylesheet" href="css/level-pages.css">

<button type="button" onclick="window.location.href='bsol/Debuter/debutant.php'">
    ← Retour au niveau débutant
</button>

<article>
    <header>
        <h1>Coupes en défense</h1>
    </header>

    <div class="course-header">
        <button class="secondary outline" disabled title="Bientôt disponible">
            <i class="fas fa-chalkboard-teacher"></i> Cours à venir
        </button>
    </div>

    <details class="level-folder">
        <summary>33 - Coupes en défense (35 donnes)</summary>
        <div class="lesson-list">
            <div class="lesson-item"><span>Donne 1</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=wr9HjdAY" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_1.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 2</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=EGbBqdfL" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_2.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 3</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=SxGAPJDF" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_3.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 4</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=CxurpzAi" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_4.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 5</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=r26WpQcb" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_5.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 6</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=Q2VUw8da" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_6.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 7</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=8YxLARa6" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_7.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 8</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=ZWX7yE4Y" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_8.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 9</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=zyEfY6ai" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_9.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 10</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=RzaUrNZ8" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_10.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 11</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=GYZ26Why" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_11.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 12</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=Gun3pLer" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_12.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 13</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=m7fFN9ir" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_13.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 14</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=kYwC9iy5" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_14.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 15</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=QjYt6Z9C" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_15.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 16</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=V27AaZGB" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_16.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 17</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=3FWeYH2b" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_17.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 18</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=5FCrb3eh" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_18.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 19</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=mATzeg6t" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_19.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 20</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=ecDLYRW6" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_20.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 21</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=zXG3cFJi" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_21.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 22</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=nvPGukgA" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_22.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 23</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=GVerqxZf" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_23.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 24</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=6CxqUwDA" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_24.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 25</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=T9ZYxqDw" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_25.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 26</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=WqCSzRHx" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_26.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 27</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=4XrNkUjC" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_27.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 28</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=wWj4LZc7" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_28.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 29</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=JCWwR4ys" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_29.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 30</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=vEq6YQSV" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_30.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 31</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=tSq825sc" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_31.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 32</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=TwKrCX4n" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_32.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 33</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=3fuy8wi5" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_33.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 34</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=YJgHKdVi" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_34.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 35</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=jhV78x6t" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/DA/3_-_Coupes_en_defense/Donne_35.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
        </div>
    </details>
</article>

<?php include '../../../includes/footer.php'; ?>
