<?php
include '../../../includes/header.php'; ?>
<link rel="stylesheet" href="css/level-pages.css">

<button type="button" onclick="window.location.href='bsol/Debuter/debutant.php'">
    ← Retour au niveau débutant
</button>

<article>
    <header>
        <h1>Les premières impasses</h1>
    </header>

    <div class="course-header">
        <a href="https://docs.google.com/presentation/d/1cg7ezV1xEXUwyi8VGgbhynyvfgOQGCGBkTjl5zLjGz0/edit?slide=id.p1#slide=id.p1" target="_blank" role="button" class="secondary">
            <i class="fas fa-chalkboard-teacher"></i> Voir le cours complet (Présentation)
        </a>
    </div>

    <details class="level-folder">
        <summary>5 - Les premières impasses (40 donnes)</summary>
        <div class="lesson-list">
            <div class="lesson-item"><span>Donne 1</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=4QMyTvNC" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_1.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 2</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=ikSUwhNR" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_2.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 3</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=xfP59uZw" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_3.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 4</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=ipwcB3dE" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_4.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 5</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=4eyhnfSE" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_5.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 6</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=KiVLAgPB" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_6.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 7</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=RhnvguUa" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_7.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 8</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=VTSHgkNf" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_8.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 9</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=hJRXvzbZ" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_9.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 10</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=fSwjBUCs" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_10.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 11</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=mWjSK7Ec" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_11.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 12</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=mWjSK7Ec" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_12.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 13</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=qrmEQCKV" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_13.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 14</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=FMjdSiN4" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_14.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 15</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=LDfGJ5t6" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_15.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 16</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=RVrL3cna" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_16.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 17</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=agQvSykW" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_17.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 18</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=Hqtp6RSZ" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_18.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 19</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=cVPsZdzB" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_19.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 20</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=fWg2CSqh" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_20.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 21</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=X8UrKTq2" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_21.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 22</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=hbkCDgr7" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_22.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 23</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=v4cDMp7m" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_23.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 24</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=WYmidcC2" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_24.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 25</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=8LxDtdG6" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_25.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 26</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=PVHL4gzR" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_26.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 27</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=MCu5bDWp" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_27.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 28</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=w9CZ4BXD" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_28.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 29</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=Gixc3Lmj" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_29.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 30</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=pujhPmAZ" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_30.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 31</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=ZpXefgEM" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_31.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 32</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=GQLmbwvJ" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_32.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 33</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=Dz2P7m8V" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_33.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 34</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=csBz9abw" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_34.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 35</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=rLNg6MSw" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_35.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 36</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=LB2WAsgn" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_36.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 37</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=JxFqWjyC" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_37.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 38</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=KWxFDzUi" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_38.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 39</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=RfHaZp4t" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_39.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
            <div class="lesson-item"><span>Donne 40</span><div class="lesson-actions"><a href="https://bridge-training.com/player?dds=kmML9JGZ" target="_blank" role="button" class="outline">Jouer</a><a href="https://freebridge.fr/ddummy.htm?file=https://freebridge.fr/bsol/Debuter/JMSA/5_-_Les_impasses/Donne_40.lin" target="_blank" role="button" class="secondary outline">Solution</a></div></div>
        </div>
    </details>

    <!-- VIDEO SECTION -->
    <details class="level-folder">
        <summary>Correction en Vidéo</summary>
        <div style="padding: 1rem; text-align: center;">
            <iframe width="100%" height="315" src="https://www.youtube.com/embed/S_8qKx8XQ-w" frameborder="0" allowfullscreen></iframe>
        </div>
    </details>
</article>

<?php include '../../../includes/footer.php'; ?>
